version: "3.9"

services:
  db:
    image: mariadb:11
    container_name: metari-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: metari_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3309:3306"

  backend:
    build: ./backend
    container_name: metari-backend
    restart: always
    ports:
      - "3008:3001"
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: metari_db
    depends_on:
      - db
    command: >
      sh -c "
      echo 'Waiting for DB...';
      until node -e \"require('mysql2/promise').createConnection({host:'db',user:'user',password:'password'}).then(c=>c.end())\"; do
        sleep 2;
      done;
      npm run migrate:apply &&
      npm run seed &&
      npm start
      "

  frontend:
    build: ./metari-app
    container_name: metari-frontend
    restart: always
    ports:
      - "8087:80"
    depends_on:
      - backend

  phpmyadmin:
    image: phpmyadmin:5.2.3-apache
    container_name: metari_phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
    ports:
      - "8089:80"

volumes:
  db_data: