@startuml
left to right direction

' Entitats principals (buïdes)
entity "Usuari" as Usuari
entity "Grup" as Grup
entity "Meta" as Meta
entity "Categoria" as Categoria

entity "Assignacio" as Assignacio
entity "Comentari" as Comentari
entity "Proofs" as Proofs
entity "Invitacio" as Invitacio
entity "Indexar" as Assignacio


<> AssignacioRel
<> InvitacioRel
<> indexarRel

Usuari }|--o{ Grup : "te"
Usuari ||--o{ Grup : "crea"
Usuari }|--o{ Grup : "administra"
Usuari ||--o{ Meta : "autor"
Usuari ||-- AssignacioRel : "assignat"
Usuari ||--o{ Comentari : "fa comentari"
Usuari ||--o{ Proofs : "fa prova"
Usuari ||-- InvitacioRel : "rep"
Usuari ||-- InvitacioRel : "envia"
Usuari ||-- indexarRel : "indexa (posa al grup)"
Usuari ||--|| Indexar : "verifica"

Grup }|--o{ Meta : "conté"
Grup ||-- AssignacioRel : "assignat"
Grup ||-- InvitacioRel : "grup"
Grup ||-- indexarRel : ""

Meta }|--|{ Categoria : "té"
Meta ||-- AssignacioRel : "assignat"
Meta ||-- indexarRel : ""
Assignacio ||--o{ Comentari : "té comentari"
' Meta ||--o{ Proofs : "té prova"

Proofs ||--|| Assignacio : a una
Assignacio }|.. AssignacioRel
Invitacio ||.. InvitacioRel 
Indexar ||.. indexarRel 




@enduml